apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: {{ template "traefik.fullname" . }}-https-redirect-middleware
  annotations:
    helm.sh/hook: "post-install,post-upgrade"
  labels:
    app.kubernetes.io/name: {{ template "traefik.name" . }}
    helm.sh/chart: {{ template "traefik.chart" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  redirectScheme:
    scheme: https
    permanent: true
  